name: qr_hub
description: "An advanced QR scanner and generator android application."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  url_launcher: ^6.2.5
  app_settings: ^5.1.1
  permission_handler: ^11.3.0
  share_plus: ^7.2.2
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  lecle_downloads_path_provider: ^0.0.2+8
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

flutter_launcher_icons:
  android: true
  image_path: "images/icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
